parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:import/typescript
rules:
  no-param-reassign: "off"
  import/extensions:
    - error
    - ignorePackages
    - js: never
      mjs: never
      jsx: never
      ts: never
  import/prefer-default-export: 'off'
  import/no-default-export:
    - error
  no-unused-expressions: 'off'
